{{- if .Values.secrets.dbPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rupaya.fullname" . }}-db
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.secrets.dbPassword | quote }}
{{- end }}